name: Release Helm Charts

on:
  push:
    branches:
      - master
      - 'release-**'
    paths:
      - "charts/**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config: .github/cr.yaml

  generate-sbom:
    runs-on: ubuntu-latest

    permissions: {}

    name: Install bom and test presence in path
    steps:
      - name: Install bom
        uses: puerco/release-actions/setup-bom@main
        with:
          bom-release: '0.5.1'
      - name: Check install!
        run: bom version
